#
# Module manifest for module 'PSGet_PSDownloader'
#
# Generated by: LordBubbles
#
# Generated on: 15/01/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSDownloader.psm1'

# Version number of this module.
ModuleVersion = '1.1.2'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '05862360-6d8e-4879-adf4-566e5f6029ac'

# Author of this module
Author = 'LordBubbles'

# Copyright statement for this module
Copyright = '(c) 2025 LordBubbles. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A PowerShell module for downloading files with multi-threaded support. Features include progress reporting, hash verification, automatic retries, pipeline support, and multiple user agent options.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Start-Download'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'PSDownloader.psm1',
    'Public\Start-Download.ps1',
    'LICENSE',
    'README.md',
    'en-US\about_PSDownloader.help.txt'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'download','multithread','http','file-transfer','downloader','multi-thread','hash-verification','powershell'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/LordBubblesDev/PSDownloader'

        #ReadmeUri of this module
        ReadmeUri = 'https://github.com/LordBubblesDev/PSDownloader/blob/main/README.md'

        # License of the module
        LicenseUri = 'https://github.com/LordBubblesDev/PSDownloader/blob/main/LICENSE'

        # Add documentation property
        PackageReadmeFile = 'README.md'

        # Set licence acceptance requirement
        PackageRequireLicenseAcceptance = $false

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @"
1.1.2 - Fixed some metadata issues.
1.1.1 - Fixed issue with Win32Api not being available on systems without .NET 4.5 or later.
1.1.0 - Added documentation for the module.
1.0.9 - Fixed timeout setting not properly applied to simple download operations. Changed to unthreaded download by default.
1.0.8 - More consistent progress report layout on the unthreaded download operation (can be called directly with '-Threads 0').
1.0.7 - Improved simple download operations (unthreaded), and added total downloaded bytes to progress reporting.
1.0.6 - Fixed issue with downloading files from servers that don't support range requests or do not provide a content length.
1.0.5 - Added a workflow to automatically publish the module to the PowerShell Gallery.
1.0.4 - Truly exclude .git folder from the module this time.
1.0.3 - Failed attempt at excluding .git folder from the module.
1.0.2 - Added support for CRC32 file integrity checks.
1.0.1 - Reupload of initial release with documentation.
1.0.0 - Initial release.
"@

        Files = @(
            'PSDownloader.psm1',
            'Public\Start-Download.ps1',
            'LICENSE',
            'README.md',
            'en-US\about_PSDownloader.help.txt'
        )

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/LordBubblesDev/PSDownloader/blob/main/README.md'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

